version: "2.1"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - /path/to/main/filebrowser/folder/:/srv
      - /path/to/database/database.db:/database.db
      - /path/to/configuration/filebrowser.json:/filebrowser.json
    ports:
      - 8080:80
      
      
networks:
  default:
    external:
      name: nginx_proxy
