version: '3.3'

services:
  
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    volumes:
      - '/:/host:ro,rslave'
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9091:9090' 
    volumes:
      - '/path/to/your/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml' # change here
        
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3457:3000'
      
networks: 
   default: 
     external: 
       name: nginx_proxy
