version: '3.3'

networks:
  nginx_proxy:
    external: true
  backend:
    external: true


services:
  
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - nginx_proxy
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9091:9090' #modify 9091 to your setup needs
    volumes:
      - '/home/ubuntu/webFM/srv/Configs/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml' #modify the path for your install location
    networks:
      - nginx_proxy
        
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3457:3000' #modify 3457 to your setup needs
    networks:
      - nginx_proxy
