version: '3.3'

networks:
  nginx_proxy:
    external: true
  backend:
    external: true


services:
  
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - backend
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9091:9090' 
    volumes:
      - '/path/to/your/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml' # change here
    networks:
      - nginx_proxy
        
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3457:3000'
    networks:
      - nginx_proxy
