#| HOMEPAGE      |#
#| CONFIGURATION |#

title: "Dashboard"
subtitle: "Services"
#logo: "logo.png"
icon: "fab fa-phoenix-framework" # Optional icon. See https://fontawesome.com/icons/

header: true
footer: 'Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide


# Optional theme customization
theme: default
colors:

  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"

  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"


links:

  - name: "Oracle Cloud"
    icon: "fas fa-cloud"
    url: "https://cloud.oracle.com/compute/instances/ocid1.instance.oc1.eu-amsterdam-1.anqw2ljrdfcgvqycwe6okoszxvohgiihqkqd3a2bddrlsnad6a4qpjr>    target: "_blank" # optional html a tag target attribute

  - name: "CloudFlare"
    icon: "fab fa-cloudflare"
    url: "https://dash.cloudflare.com/e9a345c2e417f31ca22bea5ac5e4038c/xrandhz.tech/dns"
    target: "_blank"

services:


  - name: "Cloud"
    icon: "fas fa-cloud"
    items:

      - name: "Nextcloud"
        logo: "assets/tools/nextcloud.png"
        subtitle: "Personal cloud"
        url: "url"
        type: Ping
        target: "_blank" # optional html a tag target attribute

      - name: "Plex"
        logo: "assets/tools/plex.png"
        subtitle: "Media server"
        url: "https://plex.xrandhz.tech"

      - name: "Calibre"
        logo: "assets/tools/calibre.png"
        subtitle: "Digital book library"
        url: "url"
        target: "_blank"

  - name: "Network"
    icon: "fas fa-network-wired"
    items:

      - name: "OpenVPN"
        logo: "assets/tools/openvpn.png"

      - name: "Proxy Manager"
        logo: "assets/tools/npm.png"
        url: "url"
        type: Ping
        subtitle: "Reverse proxy manager"

      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        url: "url"
        type: Ping
        subtitle: "Docker containers manager"
