version: '2'


networks:
  nginx_proxy:
    external: true
  backend:
    external: true

services:
  db:
    image: mariadb:latest
    restart: "unless-stopped"
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    networks:
      - backend
    volumes:
      - /path/to/your/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_password  #change here
      - MYSQL_PASSWORD=mysql_password  #change here
      - MYSQL_DATABASE=mysql_db_name  #change here
      - MYSQL_USER=mysql_user  #change here

  app:
    image: nextcloud:latest
    container_name: nextcloud
    restart: "unless-stopped"
    ports:
      - 8888:80
    links:
      - db
    volumes:
       - /path/to/your/nextcloud/data:/var/www/html
    environment:
      - MYSQL_PASSWORD=mysql_password  #change here
      - MYSQL_DATABASE=mysql_db_name   #change here
      - MYSQL_USER=mysql_user  #change here
      - MYSQL_HOST=db
    networks:
      - nginx_proxy
      - backend
