version: "2.1"

services: 
   
   calibre-web: 
     image: lscr.io/linuxserver/calibre-web:arm64v8-latest #change here if there are incompatibility problems 
     container_name: calibre-web 
     environment: 
       - PUID=1000 
       - PGID=1000 
       - TZ=Europe/Amsterdam #TimeZone 
       - DOCKER_MODS=linuxserver/calibre-web:calibre #optional 
       - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional 
     volumes: 
       - /path/to/your/calibre/config/:/config  #change here 
       - /path/to/your/books/folder/:/books  #change here 
     ports: 
       - 8083:8083 
     restart: unless-stopped 

networks: 
   default: 
     external: 
       name: nginx_proxy
