version: "3"

services:
  node-red:
    user: "0:0"
    container_name: node-red
    image: nodered/node-red:latest
    ports: 
      - 1880:1880
    volumes:
      - /path/to/node-red/data/folder:/data
    environment:
      - TZ=Europe/Amsterdam
    restart: always 
    

networks: 
   default: 
     external: 
       name: nginx_proxy